### ISSUE TITLE
Produktfremstilling skal skrives og billeder skal vælges

### ISSUE THREAD

**Issue by zlepper** [zlepper/Broen-Til-Fremtiden#2]

**Comment by OTGLollipop** [comment]
Der mangler nu ikke andet end et billede til sektion 2.
Jeg ville have lavet et billede, hvor første og anden iteration af boksen er sat op over for hinanden, med en pil der peger fra den gamle til den nye boks. Jeg kan dog ikke gøre dette ATM, da den computer jeg arbejder på ikke kan redigere de store billedfiler.
Jeg ville sætte pris på, hvis nogen enten lavede det billede eller fandt et alternativ.

**Comment by zlepper** [comment]
Det gør jeg i produktfastlæggelsen, så det skal du ikke bekymre dig om :)
